apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 657566734724.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:v1
          ports:
            - containerPort: 5000
